### PR TITLE
Fix generate_custom_report_prompt language bug

### PR DESCRIPTION
**Pull request by winsonluk**
```
[ERROR] 2024-12-20 07:13:06 - Error in _get_report
Exception details: generate_custom_report_prompt() got an unexpected keyword argument 'language'
Traceback:
Traceback (most recent call last):
  File "ask_gptr.py", line 50, in _get_report
    report = await researcher.write_report()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "gpt-researcher/gpt_researcher/agent.py", line 104, in write_report
    return await self.report_generator.write_report(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "gpt-researcher/gpt_researcher/skills/writer.py", line 76, in write_report
    report = await generate_report(**report_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "gpt-researcher/gpt_researcher/actions/report_generation.py", line 232, in generate_report
    content = f"{generate_prompt(query, context, report_source, report_format=cfg.report_format, tone=tone, total_words=cfg.total_words, language=cfg.language)}"
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: generate_custom_report_prompt() got an unexpected keyword argument 'language'
```

Fixing bug introduced in https://github.com/assafelovic/gpt-researcher/pull/1026

Similar to https://github.com/assafelovic/gpt-researcher/pull/1029

### CODE REVIEW

**Comment by winsonluk** [comment]
@assafelovic The language argument bug was introduced in https://github.com/assafelovic/gpt-researcher/pull/1026 - this PR and https://github.com/assafelovic/gpt-researcher/pull/1029 fix some missing argument bugs.

I haven't checked to see if there are any other similar bugs, so it's probably worth it to double check if you have the bandwidth. Thanks!

**Review by assafelovic — APPROVED** [review]
