### ISSUE TITLE
Bug introduced with commit cc9f73ad1338466b1cc0b97e7de68ce142f3195b

### ISSUE THREAD

**Issue by badcom** [assafelovic/gpt-researcher#971]
**Describe the bug**
"AttributeError: 'Config' object has no attribute 'llm_provider'"

**To Reproduce**
1. Clone the repository
2. create a .env file with these items:
OPENAI_API_KEY=
TAVILY_API_KEY=
GOOGLE_API_KEY=
GOOGLE_CX_KEY=
SEARX_URL=https://search.inetol.net
RETRIEVER=tavily,google,arxiv
3. Launch the application and run a research

**Expected behavior**
No errors after research is complete.

**Screenshots**
![2024-10-31_17-23-59](https://github.com/user-attachments/assets/d7090399-71ad-4fbf-97f8-46d43a91f6c1)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Google Chrome
 - 130.0.6723.70

**Additional context**
This bug was introduced with this commit at line 32:

https://github.com/assafelovic/gpt-researcher/commit/cc9f73ad1338466b1cc0b97e7de68ce142f3195b#diff-bff92475d4c1001924fb116017339845eac4ad312904c79ff0bf1ec6b9e22269R32

**Comment by Tovli** [comment]
Experiencing this as well

**Comment by ElishaKay** [comment]
True.

[Fixed in this commit.](https://github.com/assafelovic/gpt-researcher/commit/143eb7d547351b28520e646826c22e335d950f22#diff-bff92475d4c1001924fb116017339845eac4ad312904c79ff0bf1ec6b9e22269) 🫡
