### ISSUE TITLE
ImportError: lxml.html.clean module is now a separate project lxml_html_clean.

### ISSUE THREAD

**Issue by ParkJaeSeong** [assafelovic/gpt-researcher#418]
Thank you for the great program. 

An execution error occurred in docker after the recent git pull.

Both pip and poetry have been updated.

Please help.

Mac M1 Sonoma 14.1.2
python 3.11.8


```
[+] Building 2.1s (14/14) FINISHED                                                                                                                                                                                         docker:desktop-linux
 => [gpt-researcher internal] load build definition from Dockerfile                                                                                                                                                                        0.0s
 => => transferring dockerfile: 1.00kB                                                                                                                                                                                                     0.0s
 => [gpt-researcher internal] load metadata for docker.io/library/python:3.11.4-slim-bullseye                                                                                                                                              2.1s
 => [gpt-researcher internal] load .dockerignore                                                                                                                                                                                           0.0s
 => => transferring context: 44B                                                                                                                                                                                                           0.0s
 => [gpt-researcher install-browser 1/3] FROM docker.io/library/python:3.11.4-slim-bullseye@sha256:40319d0a897896e746edf877783ef39685d44e90e1e6de8d964d0382df0d4952                                                                        0.0s
 => [gpt-researcher internal] load build context                                                                                                                                                                                           0.0s
 => => transferring context: 9.85kB                                                                                                                                                                                                        0.0s
 => CACHED [gpt-researcher install-browser 2/3] RUN apt-get update     && apt-get satisfy -y     "chromium, chromium-driver (>= 115.0)"     && chromium --version && chromedriver --version                                                0.0s
 => CACHED [gpt-researcher install-browser 3/3] RUN apt-get install -y firefox-esr wget     && wget https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz     && tar -xvzf geckodriver*      0.0s
 => CACHED [gpt-researcher gpt-researcher-install 1/4] RUN mkdir /usr/src/app                                                                                                                                                              0.0s
 => CACHED [gpt-researcher gpt-researcher-install 2/4] WORKDIR /usr/src/app                                                                                                                                                                0.0s
 => CACHED [gpt-researcher gpt-researcher-install 3/4] COPY ./requirements.txt ./requirements.txt                                                                                                                                          0.0s
 => CACHED [gpt-researcher gpt-researcher-install 4/4] RUN pip install -r requirements.txt                                                                                                                                                 0.0s
 => CACHED [gpt-researcher gpt-researcher 1/2] RUN useradd -ms /bin/bash gpt-researcher     && chown -R gpt-researcher:gpt-researcher /usr/src/app                                                                                         0.0s
 => CACHED [gpt-researcher gpt-researcher 2/2] COPY --chown=gpt-researcher:gpt-researcher ./ ./                                                                                                                                            0.0s
 => [gpt-researcher] exporting to image                                                                                                                                                                                                    0.0s
 => => exporting layers                                                                                                                                                                                                                    0.0s
 => => writing image sha256:e30fef6b8c1ed12138be6f3aba46c4b2bccd8d9f9bba082513b365ebd1c88518                                                                                                                                               0.0s
 => => naming to docker.io/assafelovic/gpt-researcher                                                                                                                                                                                      0.0s
[+] Running 2/1
 ✔ Network gpt-researcher_default             Created                                                                                                                                                                                      0.0s
 ✔ Container gpt-researcher-gpt-researcher-1  Created                                                                                                                                                                                      0.0s
Attaching to gpt-researcher-1
gpt-researcher-1  | Traceback (most recent call last):
gpt-researcher-1  |   File "/usr/local/bin/uvicorn", line 8, in <module>
gpt-researcher-1  |     sys.exit(main())
gpt-researcher-1  |              ^^^^^^
gpt-researcher-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
gpt-researcher-1  |     return self.main(*args, **kwargs)
gpt-researcher-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
gpt-researcher-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
gpt-researcher-1  |     rv = self.invoke(ctx)
gpt-researcher-1  |          ^^^^^^^^^^^^^^^^
gpt-researcher-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
gpt-researcher-1  |     return ctx.invoke(self.callback, **ctx.params)
gpt-researcher-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gpt-researcher-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
gpt-researcher-1  |     return __callback(*args, **kwargs)
gpt-researcher-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
gpt-researcher-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 409, in main
gpt-researcher-1  |     run(
gpt-researcher-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 575, in run
gpt-researcher-1  |     server.run()
gpt-researcher-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 65, in run
gpt-researcher-1  |     return asyncio.run(self.serve(sockets=sockets))
gpt-researcher-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gpt-researcher-1  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
gpt-researcher-1  |     return runner.run(main)
gpt-researcher-1  |            ^^^^^^^^^^^^^^^^
gpt-researcher-1  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
gpt-researcher-1  |     return self._loop.run_until_complete(task)
gpt-researcher-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gpt-researcher-1  |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
gpt-researcher-1  |     return future.result()
gpt-researcher-1  |            ^^^^^^^^^^^^^^^
gpt-researcher-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 69, in serve
gpt-researcher-1  |     await self._serve(sockets)
gpt-researcher-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 76, in _serve
gpt-researcher-1  |     config.load()
gpt-researcher-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 433, in load
gpt-researcher-1  |     self.loaded_app = import_from_string(self.app)
gpt-researcher-1  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gpt-researcher-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 19, in import_from_string
gpt-researcher-1  |     module = importlib.import_module(module_str)
gpt-researcher-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gpt-researcher-1  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
gpt-researcher-1  |     return _bootstrap._gcd_import(name[level:], package, level)
gpt-researcher-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gpt-researcher-1  |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
gpt-researcher-1  |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
gpt-researcher-1  |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
gpt-researcher-1  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
gpt-researcher-1  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
gpt-researcher-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
gpt-researcher-1  |   File "/usr/src/app/main.py", line 1, in <module>
gpt-researcher-1  |     from backend.server import app
gpt-researcher-1  |   File "/usr/src/app/backend/server.py", line 7, in <module>
gpt-researcher-1  |     from gpt_researcher.utils.websocket_manager import WebSocketManager
gpt-researcher-1  |   File "/usr/src/app/gpt_researcher/__init__.py", line 1, in <module>
gpt-researcher-1  |     from .master import GPTResearcher
gpt-researcher-1  |   File "/usr/src/app/gpt_researcher/master/__init__.py", line 1, in <module>
gpt-researcher-1  |     from .agent import GPTResearcher
gpt-researcher-1  |   File "/usr/src/app/gpt_researcher/master/agent.py", line 4, in <module>
gpt-researcher-1  |     from gpt_researcher.master.functions import *
gpt-researcher-1  |   File "/usr/src/app/gpt_researcher/master/functions.py", line 3, in <module>
gpt-researcher-1  |     from gpt_researcher.scraper.scraper import Scraper
gpt-researcher-1  |   File "/usr/src/app/gpt_researcher/scraper/__init__.py", line 3, in <module>
gpt-researcher-1  |     from .newspaper.newspaper import NewspaperScraper
gpt-researcher-1  |   File "/usr/src/app/gpt_researcher/scraper/newspaper/newspaper.py", line 1, in <module>
gpt-researcher-1  |     from newspaper import Article
gpt-researcher-1  |   File "/usr/local/lib/python3.11/site-packages/newspaper/__init__.py", line 10, in <module>
gpt-researcher-1  |     from .api import (build, build_article, fulltext, hot, languages,
gpt-researcher-1  |   File "/usr/local/lib/python3.11/site-packages/newspaper/api.py", line 14, in <module>
gpt-researcher-1  |     from .article import Article
gpt-researcher-1  |   File "/usr/local/lib/python3.11/site-packages/newspaper/article.py", line 15, in <module>
gpt-researcher-1  |     from . import network
gpt-researcher-1  |   File "/usr/local/lib/python3.11/site-packages/newspaper/network.py", line 14, in <module>
gpt-researcher-1  |     from .configuration import Configuration
gpt-researcher-1  |   File "/usr/local/lib/python3.11/site-packages/newspaper/configuration.py", line 15, in <module>
gpt-researcher-1  |     from .parsers import Parser
gpt-researcher-1  |   File "/usr/local/lib/python3.11/site-packages/newspaper/parsers.py", line 12, in <module>
gpt-researcher-1  |     import lxml.html.clean
gpt-researcher-1  |   File "/usr/local/lib/python3.11/site-packages/lxml/html/clean.py", line 18, in <module>
gpt-researcher-1  |     raise ImportError(
gpt-researcher-1  | ImportError: lxml.html.clean module is now a separate project lxml_html_clean.
gpt-researcher-1  | Install lxml[html_clean] or lxml_html_clean directly.
gpt-researcher-1 exited with code 1
```

**Comment by ParkJaeSeong** [comment]
Added line to Dockerfile `RUN pip install lxml[html_clean]`.
It works now, but I don't think it's a good workaround.

```
❯ cat Dockerfile
FROM python:3.11.4-slim-bullseye as install-browser

RUN apt-get update \
    && apt-get satisfy -y \
    "chromium, chromium-driver (>= 115.0)" \
    && chromium --version && chromedriver --version

RUN apt-get install -y firefox-esr wget \
    && wget https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz \
    && tar -xvzf geckodriver* \
    && chmod +x geckodriver \
    && mv geckodriver /usr/local/bin/

FROM install-browser as gpt-researcher-install

ENV PIP_ROOT_USER_ACTION=ignore

RUN mkdir /usr/src/app
WORKDIR /usr/src/app

COPY ./requirements.txt ./requirements.txt
RUN pip install -r requirements.txt
RUN pip install lxml[html_clean]

FROM gpt-researcher-install AS gpt-researcher

RUN useradd -ms /bin/bash gpt-researcher \
    && chown -R gpt-researcher:gpt-researcher /usr/src/app

USER gpt-researcher

COPY --chown=gpt-researcher:gpt-researcher ./ ./

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
```

**Comment by badcom** [comment]
I get that same error message. It works fine with python 3.10.6

**Comment by arces** [comment]
> RUN pip install lxml[html_clean]

This worked for me as well

**Comment by assafelovic** [comment]
See here for fix: https://github.com/assafelovic/gpt-researcher/pull/424

**Comment by PaddingtonTheBear** [comment]
cannot import name '_find_external_links' from 'lxml.html.clean
